samples:
    # sample or id to use for generating targets
    id_list: ["HG002_30X"]
    cram_path: "/BIGDATA2/gzfezx_shhli_2/USER/luozhenyu/20240124_EBV_Dengue/input_all"

modules:
    # Should snakemake do specific analyses
    pindel: False
    
params:
    smk_path: "/BIGDATA2/gzfezx_shhli_2/software/script/WGS_SV"
    # paths to tools used by the pipeline
    PWD: " "  # current output directory
    breakdancer: "/BIGDATA2/gzfezx_shhli_2/miniconda3/envs/breakseq2/bin"
    cnvnator: "/BIGDATA2/gzfezx_shhli_2/miniconda3/envs/cnvnator/bin"
    lumpy: "/BIGDATA2/gzfezx_shhli_2/miniconda3/envs/manta/bin"
    manta: "/BIGDATA2/gzfezx_shhli_2/miniconda3/envs/manta/bin"
    metasv: "/BIGDATA2/gzfezx_shhli_2/miniconda3/envs/manta/bin"
    pindel: "/BIGDATA2/gzfezx_shhli_2/miniconda3/envs/manta/bin"
    samtools: "/WORK2/gzfezx_shhli_3/BioSoftware/local/bin"
    annovar: "/BIGDATA2/gzfezx_shhli_2/software/annovar"
    annovar_db: "/BIGDATA2/gzfezx_shhli_2/software/annovar/humandb"
    # here we need a python3 env
    python3: "/BIGDATA2/gzfezx_shhli_2/miniconda3/envs/cnvnator/bin/python"
    # reference genome
    ref_fa: "/BIGDATA2/gzfezx_shhli_2/USER/luozhenyu/database/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa"
    ref_fa_chr: "/BIGDATA2/gzfezx_shhli_2/USER/luozhenyu/database/GRCh38/chr"
    # ref_fa: "/WORK2/gzfezx_shhli_3/BioDatahub/human_reference/GRCh37/human_g1k_v37.fasta"
    # ref_fa_chr: "/WORK2/gzfezx_shhli_3/BioDatahub/human_reference/GRCh37/GRCh37.chrom"
    # depth of bam file for calling variants
    depth: 30
    read_length: 100
    # insert size for paired-end reads, 500 for the reads length of 100-150bp
    insert_size: 500

threads: 24
